### ISSUE TITLE
Develop a feature to start a new game from the lobby UI.

### ISSUE THREAD

**Issue by usamike25** [sopra-fs24-group-33/client#13]

**Comment by kauii** [comment]
after finishing the game and clicking new game, the system breaks. cannot delete the game via rest delete request yet. sql error hindering deletion

**Comment by kauii** [comment]
delete request works now. but when all cards are out, there is no pop up showing up indicating the end of the game and the corresponding buttons leave and new game are also missing.

**Comment by kauii** [comment]
fixed issue with f8df1b5ba5efaeced394652716b3defefe504d88
& backend with c7b43001c642505b946ef754d43f179a64b61614
