### ISSUE TITLE
Create a session management system to handle user logins. / localstorage, routing

### ISSUE THREAD

**Issue by usamike25** [sopra-fs24-group-33/client#28]

**Comment by kauii** [comment]
several commits fixing routing
88ae110f85e217ded9a0dd63f48fe97c72f5b230
74a10738e5e8d76381ab8718e9630f52d96e904f
added websocket to fetch players and users data in real time
035b8be61527f0a784c3ab5f0853f886f5f472fb

**Comment by kauii** [comment]
merged into main
0c1e788f276625ff173edd2e6a6923b81d659fe8
