### ISSUE TITLE
custom error messages/boxes

### ISSUE THREAD

**Issue by Paulin3000** [sopra-fs24-group-33/client#55]

**Comment by kauii** [comment]
added error prop for the join popup to display various errors below the formfield
a7a8869839b1be83542c63f73de85af675d9f279

**Comment by kauii** [comment]
setError in register for invalid usernames and for alreadye existing usernames
61f21edc47f35bb7544a9dad76fbb3a29483dcd7

**Comment by kauii** [comment]
2b478ce34d0d24fdd8c4d6eb906ce44e6345b63e
